#!/usr/bin/env python3
"""Build Stage 2 delay path review Excel from Tcl-generated CSV sheets."""

from __future__ import print_function

import argparse
import csv
import os
import re
import sys

try:
    from openpyxl import Workbook
    from openpyxl.styles import Alignment, Border, Font, PatternFill, Side
    from openpyxl.utils import get_column_letter
except ImportError as exc:
    raise SystemExit(
        "ERROR: openpyxl is required. Please run with a Python environment that has openpyxl installed: %s"
        % exc
    )


VERSION = "v0.1.7"
TOOL_NAME = "run_stage2_report.py"
STAGE_NAME = "STA Flatten 2 Set Delay Merge PrimeTime Report"


def release_identity():
    anchors = {
        4: "report_rpt",
        1: "out_xlsx",
        5: "delay",
        0: "help",
        3: "args",
        2: "workbook",
    }
    return "".join(anchors[index][0] for index in range(len(anchors))).title()


def guarded_release_identity():
    candidate = release_identity()
    proof_anchors = {
        3: "analysis",
        0: "hierarchy",
        5: "delay",
        2: "write",
        4: "report",
        1: "object",
    }
    reference = "".join(
        proof_anchors[index][0] for index in range(len(proof_anchors))
    ).title()
    if candidate != reference:
        return "Who is your daddy?"
    return candidate


FILL_TITLE = PatternFill("solid", fgColor="1F4E78")
FILL_SUBTITLE = PatternFill("solid", fgColor="D9EAF7")
FILL_HIGHLIGHT = PatternFill("solid", fgColor="FFF2CC")
FILL_NOT_FOUND = PatternFill("solid", fgColor="F4CCCC")
FILL_NEUTRAL = PatternFill("solid", fgColor="FFFFFF")
FONT_TITLE = Font(color="FFFFFF", bold=True)
FONT_HEADER = Font(bold=True)
FONT_NORMAL = Font(color="000000")
ALIGN_CENTER = Alignment(horizontal="center", vertical="center", wrap_text=True)
ALIGN_LEFT = Alignment(horizontal="left", vertical="center", wrap_text=True)
THIN_BORDER = Border(
    left=Side(style="thin", color="B7B7B7"),
    right=Side(style="thin", color="B7B7B7"),
    top=Side(style="thin", color="B7B7B7"),
    bottom=Side(style="thin", color="B7B7B7"),
)


def print_author_banner():
    release_owner = guarded_release_identity()
    lines = [
        "============================================================",
        "  Script  : %s" % TOOL_NAME,
        "  Stage   : %s" % STAGE_NAME,
        "  Author  : %s" % release_owner,
        "  Version : %s" % VERSION,
        "============================================================",
    ]
    for line in lines:
        print(line)


def parse_args(argv):
    parser = argparse.ArgumentParser(
        description="Create Stage 2 delay path review Excel from delay_path_summary CSV bundle."
    )
    parser.add_argument(
        "summary_dir",
        nargs="?",
        default="delay_path_summary",
        help="Directory generated by run_stage2_merge_delay.tcl. Default: ./delay_path_summary",
    )
    parser.add_argument(
        "-o",
        "--out_xlsx",
        default="",
        help="Output .xlsx path. Default: <summary_dir_parent>/<TOP_SDC_basename>.xlsx",
    )
    parser.add_argument(
        "--top_module",
        default="",
        help="Top module name used for default Excel filename. Overrides TOP_SDC basename inference.",
    )
    parser.add_argument(
        "--report_rpt",
        default="",
        help="Optional integration_delay_merge.rpt path used to infer top module.",
    )
    return parser.parse_args(argv)


def read_csv_dicts(path):
    with open(path, "r", newline="") as fin:
        return list(csv.DictReader(fin))


def normalize_value(value):
    if value is None:
        return ""
    return str(value).strip()


def is_missing(value):
    value = normalize_value(value)
    return value == "" or value == "-"


def display_or_not_found(value):
    return "NOT FOUND" if is_missing(value) else value


def display_or_dash(value):
    return "-" if is_missing(value) else value


def display_id(row):
    e2e_id = normalize_value(row.get("e2e_id", ""))
    if not is_missing(e2e_id):
        return e2e_id
    path_id = normalize_value(row.get("path_id", ""))
    if not is_missing(path_id):
        return path_id
    return "-"


def safe_filename_token(text):
    token = normalize_value(text)
    if token == "" or (token.startswith("<") and token.endswith(">")):
        token = "current_integration_top"
    token = re.sub(r"[^A-Za-z0-9_.-]+", "_", token)
    token = re.sub(r"^_+|_+$", "", token)
    return token or "current_integration_top"


def top_name_from_sdc_path(path):
    base = os.path.basename(normalize_value(path))
    root, _ext = os.path.splitext(base)
    return safe_filename_token(root)


def safe_sheet_name(name, used):
    base = normalize_value(name) or "sheet"
    base = re.sub(r"[\[\]\:\*\?\/\\]", "_", base)
    base = base.strip("'") or "sheet"
    base = base[:31]
    candidate = base
    idx = 1
    while candidate in used:
        suffix = "_%d" % idx
        candidate = (base[: 31 - len(suffix)] + suffix)[:31]
        idx += 1
    used.add(candidate)
    return candidate


def infer_top_module(summary_dir, explicit_top="", report_rpt=""):
    if normalize_value(explicit_top):
        return safe_filename_token(explicit_top)

    parent_dir = os.path.dirname(os.path.abspath(summary_dir))
    rpt_candidates = []
    if normalize_value(report_rpt):
        rpt_candidates.append(report_rpt)
    rpt_candidates.append(os.path.join(parent_dir, "integration_delay_merge.rpt"))

    for rpt in rpt_candidates:
        if not os.path.exists(rpt):
            continue
        with open(rpt, "r", errors="replace") as fin:
            text = fin.read()
        match = re.search(r"^\s*Top SDC\s*:\s*(.+?)\s*$", text, re.M)
        if match:
            value = top_name_from_sdc_path(match.group(1))
            if value:
                return value
        match = re.search(r"^\s*Final flatten SDC\s*:\s*(.+?)\s*$", text, re.M)
        if match:
            base = os.path.basename(normalize_value(match.group(1)))
            if base.endswith("_flatten.sdc"):
                return safe_filename_token(base[: -len("_flatten.sdc")])
        match = re.search(r"^\s*Current PT design\s*:\s*(.+?)\s*$", text, re.M)
        if match:
            value = normalize_value(match.group(1))
            if value and not (value.startswith("<") and value.endswith(">")):
                return safe_filename_token(value)

    e2e = os.path.join(parent_dir, "generated_e2e_delay.sdc")
    if os.path.exists(e2e):
        with open(e2e, "r", errors="replace") as fin:
            text = fin.read()
        match = re.search(r"^\s*#\s*Scope\s*:\s*(.+?)\s*$", text, re.M)
        if match:
            value = normalize_value(match.group(1))
            if value and not (value.startswith("<") and value.endswith(">")):
                return safe_filename_token(value)

    return safe_filename_token(os.path.basename(parent_dir))


def index_rows(summary_dir):
    index_path = os.path.join(summary_dir, "00_index.csv")
    if not os.path.exists(index_path):
        raise SystemExit("ERROR: index CSV not found: %s" % index_path)
    rows = read_csv_dicts(index_path)
    if not rows:
        raise SystemExit("ERROR: index CSV has no sheet rows: %s" % index_path)
    return rows


def sheet_stage_count(rows):
    max_stage = 0
    for row in rows:
        for key in row:
            match = re.match(r"stage_(\d+)_sdc_delay$", key)
            if match:
                idx = int(match.group(1))
                if idx > max_stage and stage_applicable(row, idx):
                    max_stage = idx
        for key in row:
            match = re.match(r"seg_(\d+)_cmd_id$", key)
            if match and not is_missing(row.get(key, "")):
                max_stage = max(max_stage, int(match.group(1)))
    return max_stage


def row_stage_count(row):
    count = 0
    for key in row:
        match = re.match(r"stage_(\d+)_sdc_delay$", key)
        if match:
            idx = int(match.group(1))
            if stage_applicable(row, idx):
                count = max(count, idx)
    for key in row:
        match = re.match(r"seg_(\d+)_cmd_id$", key)
        if match and not is_missing(row.get(key, "")):
            count = max(count, int(match.group(1)))
    return count


def stage_applicable(row, idx):
    values = [
        row.get("stage_%d_sdc_delay" % idx, ""),
        row.get("stage_%d_from" % idx, ""),
        row.get("stage_%d_to" % idx, ""),
        row.get("seg_%d_cmd_id" % idx, ""),
    ]
    return any(not is_missing(value) for value in values)


def group_titles(max_stage_count):
    if max_stage_count <= 1:
        return ["Start Point", "End Point"]
    titles = ["Start Point"]
    for idx in range(2, max_stage_count):
        titles.append("through_%d" % (idx - 1))
    titles.append("End Point")
    return titles


def stage_for_group(group_idx, group_count, row_count):
    if group_count <= 1:
        return 1 if row_count >= 1 else 0
    if group_idx == 0:
        return 1
    if group_idx == group_count - 1:
        return row_count
    candidate = group_idx + 1
    if candidate < row_count:
        return candidate
    return 0


def group_values(row, group_idx, group_count):
    stage_count = row_stage_count(row)
    stage_idx = stage_for_group(group_idx, group_count, stage_count)
    if stage_idx <= 0 or stage_idx > stage_count:
        return "-", "-", "-", False

    if group_idx == 0:
        delay = row.get("start_sdc_delay", row.get("stage_1_sdc_delay", ""))
        from_value = row.get("start_from", row.get("stage_1_from", ""))
        to_value = row.get("start_to", row.get("stage_1_to", ""))
    elif group_idx == group_count - 1:
        delay = row.get("end_sdc_delay", row.get("stage_%d_sdc_delay" % stage_idx, ""))
        from_value = row.get("end_from", row.get("stage_%d_from" % stage_idx, ""))
        to_value = row.get("end_to", row.get("stage_%d_to" % stage_idx, ""))
    else:
        delay = row.get("stage_%d_sdc_delay" % stage_idx, "")
        from_value = row.get("stage_%d_from" % stage_idx, "")
        to_value = row.get("stage_%d_to" % stage_idx, "")

    return (
        display_or_not_found(from_value),
        display_or_not_found(to_value),
        display_or_not_found(delay),
        True,
    )


def current_stage_index(row):
    cmd_id = normalize_value(row.get("cmd_id", ""))
    source = normalize_value(row.get("source", ""))
    source_inst = normalize_value(row.get("source_inst", ""))
    if not cmd_id:
        return 0

    max_stage = max(row_stage_count(row), 1)
    for idx in range(1, max_stage + 1):
        seg_cmd = normalize_value(row.get("seg_%d_cmd_id" % idx, ""))
        if seg_cmd != cmd_id:
            continue
        seg_source = normalize_value(row.get("seg_%d_source" % idx, ""))
        seg_inst = normalize_value(row.get("seg_%d_inst" % idx, ""))
        if source and seg_source and seg_source != source:
            continue
        if source_inst and seg_inst and seg_inst != source_inst:
            continue
        return idx
    return 0


def highlighted_groups(row, group_count):
    stage_count = row_stage_count(row)
    stage_idx = current_stage_index(row)
    if stage_idx <= 0 or stage_count <= 0:
        return set()
    if stage_count == 1:
        return {0, group_count - 1}
    if stage_idx == 1:
        return {0}
    if stage_idx == stage_count:
        return {group_count - 1}
    return {stage_idx - 1}


def collapsed_display_rows(rows):
    out = []
    index = {}
    for row in rows:
        row_id = display_id(row)
        if row_id != "-" and normalize_value(row.get("merge_status", "")) in {"MERGED", "RESIDUAL"}:
            key = row_id
        else:
            key = "%s|%s|%s" % (
                row_id,
                normalize_value(row.get("path_id", "")),
                normalize_value(row.get("cmd_id", "")),
            )
        if key not in index:
            index[key] = len(out)
            out.append({"row": row, "rows": [row]})
        else:
            out[index[key]]["rows"].append(row)
    return out


def combined_highlighted_groups(rows, group_count):
    groups = set()
    for row in rows:
        groups.update(highlighted_groups(row, group_count))
    return groups


def int_or_none(value):
    value = normalize_value(value)
    if not value:
        return None
    try:
        return int(value)
    except ValueError:
        return None


def usage_label(index_item):
    used = normalize_value(index_item.get("max_delay_used", ""))
    total = normalize_value(index_item.get("max_delay_total", ""))
    total_int = int_or_none(total)
    missing = normalize_value(index_item.get("missing_sdc_stages", ""))
    if total_int == 0:
        lines = [
            "Max Delay Used: N/A",
            "Native max_delay: 0",
        ]
        if missing:
            lines.append("Missing SDC Stage: %s" % missing)
        return "\n".join(lines)
    usage = normalize_value(index_item.get("max_delay_usage", ""))
    if usage:
        return "Max Delay Used: %s" % usage
    if used and total:
        return "Max Delay Used: %s/%s" % (used, total)
    return "Max Delay Used: -"


def write_id_header(ws, index_item):
    top = ws.cell(row=1, column=1, value="E2E ID\n%s" % usage_label(index_item))
    top.fill = FILL_TITLE
    top.font = FONT_TITLE
    top.alignment = ALIGN_CENTER
    top.border = THIN_BORDER
    sub = ws.cell(row=2, column=1, value="ID")
    sub.fill = FILL_SUBTITLE
    sub.font = FONT_HEADER
    sub.alignment = ALIGN_CENTER
    sub.border = THIN_BORDER


def write_group_headers(ws, titles, index_item):
    write_id_header(ws, index_item)
    col = 2
    for title in titles:
        start_col = col
        end_col = col + 2
        ws.merge_cells(start_row=1, start_column=start_col, end_row=1, end_column=end_col)
        cell = ws.cell(row=1, column=start_col, value=title)
        cell.fill = FILL_TITLE
        cell.font = FONT_TITLE
        cell.alignment = ALIGN_CENTER
        cell.border = THIN_BORDER
        for sub_col, sub_title in enumerate(["From", "To", "Delay"], start=start_col):
            sub = ws.cell(row=2, column=sub_col, value=sub_title)
            sub.fill = FILL_SUBTITLE
            sub.font = FONT_HEADER
            sub.alignment = ALIGN_CENTER
            sub.border = THIN_BORDER
        for merged_col in range(start_col + 1, end_col + 1):
            merged = ws.cell(row=1, column=merged_col)
            merged.fill = FILL_TITLE
            merged.border = THIN_BORDER
        col += 3


def style_data_cell(cell, value, highlighted):
    cell.value = value
    cell.alignment = ALIGN_LEFT
    cell.font = FONT_NORMAL
    cell.border = THIN_BORDER
    if value == "NOT FOUND":
        cell.fill = FILL_NOT_FOUND
    elif highlighted:
        cell.fill = FILL_HIGHLIGHT
    else:
        cell.fill = FILL_NEUTRAL


def write_sheet(workbook, sheet_name, rows, used_sheet_names, index_item):
    ws = workbook.create_sheet(safe_sheet_name(sheet_name, used_sheet_names))
    max_stage = sheet_stage_count(rows)
    titles = group_titles(max_stage)
    group_count = len(titles)
    write_group_headers(ws, titles, index_item)

    if not rows:
        rows = [{}]

    display_rows = collapsed_display_rows(rows)

    for row_idx, item in enumerate(display_rows, start=3):
        row = item["row"]
        highlights = combined_highlighted_groups(item["rows"], group_count)
        style_data_cell(
            ws.cell(row=row_idx, column=1),
            display_id(row),
            False,
        )
        col = 2
        for group_idx in range(group_count):
            from_value, to_value, delay_value, applicable = group_values(row, group_idx, group_count)
            values = [from_value, to_value, delay_value]
            if not applicable:
                values = ["-", "-", "-"]
            for value in values:
                style_data_cell(ws.cell(row=row_idx, column=col), value, group_idx in highlights)
                col += 1

    max_col = 1 + group_count * 3
    ws.column_dimensions[get_column_letter(1)].width = 24
    for col_idx in range(1, max_col + 1):
        if col_idx != 1:
            ws.column_dimensions[get_column_letter(col_idx)].width = 24
    for row_idx in range(1, ws.max_row + 1):
        if row_idx == 1:
            ws.row_dimensions[row_idx].height = 72
        elif row_idx == 2:
            ws.row_dimensions[row_idx].height = 30
        else:
            ws.row_dimensions[row_idx].height = 44
    ws.freeze_panes = "B3"
    ws.sheet_view.showGridLines = False
    ws.auto_filter.ref = "A2:%s%d" % (get_column_letter(max_col), ws.max_row)
    return ws


def build_workbook(summary_dir):
    rows = index_rows(summary_dir)
    workbook = Workbook()
    workbook.remove(workbook.active)
    used_sheet_names = set()

    for item in rows:
        sheet = normalize_value(item.get("sheet", ""))
        csv_file = normalize_value(item.get("file", ""))
        if not sheet or not csv_file:
            continue
        csv_path = os.path.join(summary_dir, csv_file)
        if not os.path.exists(csv_path):
            raise SystemExit("ERROR: sheet CSV not found: %s" % csv_path)
        sheet_rows = read_csv_dicts(csv_path)
        write_sheet(workbook, sheet, sheet_rows, used_sheet_names, item)

    if not workbook.sheetnames:
        raise SystemExit("ERROR: no workbook sheets were created from %s" % summary_dir)
    return workbook


def main(argv):
    args = parse_args(argv)
    print_author_banner()

    summary_dir = os.path.abspath(args.summary_dir)
    if not os.path.isdir(summary_dir):
        raise SystemExit("ERROR: summary_dir not found: %s" % summary_dir)

    top_module = infer_top_module(summary_dir, args.top_module, args.report_rpt)
    out_xlsx = args.out_xlsx
    if not normalize_value(out_xlsx):
        out_xlsx = os.path.join(os.path.dirname(summary_dir), "%s.xlsx" % top_module)
    out_xlsx = os.path.abspath(out_xlsx)
    if not out_xlsx.endswith(".xlsx"):
        out_xlsx += ".xlsx"

    workbook = build_workbook(summary_dir)
    parent = os.path.dirname(out_xlsx)
    if parent and not os.path.isdir(parent):
        os.makedirs(parent)
    workbook.save(out_xlsx)

    print("INFO: Summary CSV dir : %s" % summary_dir)
    print("INFO: Top module      : %s" % top_module)
    print("INFO: Output Excel    : %s" % out_xlsx)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
