################################################################################
# Auto-generated integration E2E delay SDC
#
# ============================================================
#   Script  : run_stage2_merge_delay.tcl
#   Stage   : STA Flatten 2 Set Delay Merge PrimeTime
#   Author  : Howard
#   Version : v0.7.3
# ============================================================
#
# Generated by             : run_stage2_merge_delay.tcl
# E2E_DELAY_MERGE_VERSION  : v0.7.3
# Scope                    : path_summary_recursive
#
# This file is generated for the current integration top scope.
# If this integration top is later consumed as a harden by an upper-level SoC,
# this file shall be reprocessed by Stage 1 hierarchy mapper.
################################################################################

# MERGED top=CMD000001 harden=CMD000002+CMD000003 boundary=u_h0/cfg_i
set_max_delay 8 -from [get_pins {u_up/u_reg/Q}] -to [get_pins {u_h0/u_reg/D}]

