# ============================================================
#   Script  : run_stage2_merge_delay.tcl
#   Stage   : STA Flatten 2 Set Delay Merge PrimeTime
#   Author  : Howard
#   Version : v0.7.3
# ============================================================
#
# merged_delay_removed.sdc generated by run_stage2_merge_delay.tcl
# CONSUMED /Users/howard/Documents/33_vcspyglass sdc处理/soc_sdc_work/STA Flatten 2 Set Delay Merge PrimeTime脚本/demo_case/path_summary_recursive/top_dc.sdc|CMD000001 original_id=CMD000001 split=1/1
set_max_delay 2.0      -from [get_pins u_up/data_o]      -to [get_pins u_h0/cfg_i]

# CONSUMED /Users/howard/Documents/33_vcspyglass sdc处理/soc_sdc_work/STA Flatten 2 Set Delay Merge PrimeTime脚本/demo_case/path_summary_recursive/up_clean.sdc|CMD000002 original_id=CMD000002 split=1/1
set_max_delay 1.0      -from [get_pins u_up/u_reg/Q]      -to [get_pins u_up/data_o]

# CONSUMED /Users/howard/Documents/33_vcspyglass sdc处理/soc_sdc_work/STA Flatten 2 Set Delay Merge PrimeTime脚本/demo_case/path_summary_recursive/harden0_clean.sdc|CMD000003 original_id=CMD000003 split=1/1
set_max_delay 5.0      -from [get_pins u_h0/cfg_i]      -to [get_pins u_h0/u_reg/D]

