# ============================================================
#   Script  : run_stage2_merge_delay.tcl
#   Stage   : STA Flatten 2 Set Delay Merge PrimeTime
#   Author  : Howard
#   Version : v0.7.3
# ============================================================
#
# path_summary_recursive_flatten.sdc generated by run_stage2_merge_delay.tcl
#
# This file is a flattened Stage 2 final SDC for the current integration scope.
# It contains:
#   1. top SDC content after removing consumed delay constraints
#   2. Stage 2 generated E2E delay constraints
#   3. each harden clean SDC after removing consumed delay constraints
#
# Do not source merged_delay_removed.sdc. It is only an audit file.

################################################################################
# TOP_REMAINING_SDC
# Source: /Users/howard/Documents/33_vcspyglass sdc处理/soc_sdc_work/STA Flatten 2 Set Delay Merge PrimeTime脚本/demo_case/path_summary_recursive/top_dc.sdc
################################################################################
# Recursive path-summary demo top delay.
#
# This top segment connects upstream harden output to downstream harden input.
# STAGE2_CONSUMED CMD000001: original delay moved to merged_delay_removed.sdc

################################################################################
# GENERATED_E2E_DELAY_SDC
# Source: /Users/howard/Documents/33_vcspyglass sdc处理/soc_sdc_work/STA Flatten 2 Set Delay Merge PrimeTime脚本/demo_case/path_summary_recursive/generated_e2e_delay.sdc
################################################################################
# MERGED top=CMD000001 harden=CMD000002+CMD000003 boundary=u_h0/cfg_i
set_max_delay 8 -from [get_pins {u_up/u_reg/Q}] -to [get_pins {u_h0/u_reg/D}]


################################################################################
# HARDEN_REMAINING_SDC inst=u_up
# Source: /Users/howard/Documents/33_vcspyglass sdc处理/soc_sdc_work/STA Flatten 2 Set Delay Merge PrimeTime脚本/demo_case/path_summary_recursive/up_clean.sdc
################################################################################
# Upstream harden clean SDC.
# STAGE2_CONSUMED CMD000002: original delay moved to merged_delay_removed.sdc

################################################################################
# HARDEN_REMAINING_SDC inst=u_h0
# Source: /Users/howard/Documents/33_vcspyglass sdc处理/soc_sdc_work/STA Flatten 2 Set Delay Merge PrimeTime脚本/demo_case/path_summary_recursive/harden0_clean.sdc
################################################################################
# Downstream harden clean SDC.
# STAGE2_CONSUMED CMD000003: original delay moved to merged_delay_removed.sdc

