# ============================================================
#   Script  : run_stage2_merge_delay.tcl
#   Stage   : STA Flatten 2 Set Delay Merge PrimeTime
#   Author  : Howard
#   Version : v0.4
# ============================================================
#
# deep_multi_mapping_flatten.sdc generated by run_stage2_merge_delay.tcl
#
# This file is a flattened Stage 2 final SDC for the current integration scope.
# It contains:
#   1. top SDC content after removing consumed delay constraints
#   2. Stage 2 generated E2E delay constraints
#   3. each harden clean SDC after removing consumed delay constraints
#
# Do not source merged_delay_removed.sdc. It is only an audit file.

################################################################################
# TOP_REMAINING_SDC
# Source: /Users/howard/Documents/33_vcspyglass sdc处理/soc_sdc_work/STA Flatten 2 Set Delay Merge PrimeTime脚本/demo_case/deep_multi_mapping/top_dc.sdc
################################################################################
# Deep demo top integration delay segments.
#
# This case intentionally uses multi-object -from/-to lists to exercise
# Stage 2 v0.4 pair expansion and partial leftover rewriting.

# Case A:
# Two legal top startpoints drive three harden input boundary pins.
# cfg_i and mode_i have matching harden internal delay segments.
# unused_i does not, so those two top pairs must remain in final SDC.
# STAGE2_REWRITTEN CMD000001: original multi-object delay kept only for unmerged pairs
# STAGE2_ORIGINAL: set_max_delay 2.0 -from [list [get_pins u_src0/Q] [get_pins u_src1/Q]] -to [list [get_pins u_h0/cfg_i] [get_pins u_h0/mode_i] [get_pins u_h0/unused_i]]
set_max_delay 2 -from [get_pins {u_src0/Q}] -to [get_pins {u_h0/unused_i}]
set_max_delay 2 -from [get_pins {u_src1/Q}] -to [get_pins {u_h0/unused_i}]

# Case B:
# Top open_from to two boundary pins. Matching harden min delay should produce
# two conservative -through E2E constraints.
# STAGE2_CONSUMED CMD000002: original delay moved to merged_delay_removed.sdc

# Case C:
# This top segment points to a harden input whose harden-side delay exits the
# harden through an output boundary. Stage 2 should review it, not merge it.
set_max_delay 1.0 \
    -from [get_pins u_src2/Q] \
    -to [get_pins u_h0/pass_i]

################################################################################
# GENERATED_E2E_DELAY_SDC
# Source: /Users/howard/Documents/33_vcspyglass sdc处理/soc_sdc_work/STA Flatten 2 Set Delay Merge PrimeTime脚本/demo_case/deep_multi_mapping/generated_e2e_delay.sdc
################################################################################
# MERGED top=CMD000001.001 harden=CMD000004.001 boundary=u_h0/cfg_i
set_max_delay 7 -from [get_pins {u_src0/Q}] -to [get_pins {u_h0/u_cfg_reg/D}]

# MERGED top=CMD000001.004 harden=CMD000004.001 boundary=u_h0/cfg_i
set_max_delay 7 -from [get_pins {u_src1/Q}] -to [get_pins {u_h0/u_cfg_reg/D}]

# MERGED top=CMD000001.001 harden=CMD000004.002 boundary=u_h0/cfg_i
set_max_delay 7 -from [get_pins {u_src0/Q}] -to [get_pins {u_h0/u_cfg_shadow_reg/D}]

# MERGED top=CMD000001.004 harden=CMD000004.002 boundary=u_h0/cfg_i
set_max_delay 7 -from [get_pins {u_src1/Q}] -to [get_pins {u_h0/u_cfg_shadow_reg/D}]

# MERGED top=CMD000001.002 harden=CMD000005 boundary=u_h0/mode_i
set_max_delay 8 -from [get_pins {u_src0/Q}] -to [get_pins {u_h0/u_mode_reg/D}]

# MERGED top=CMD000001.005 harden=CMD000005 boundary=u_h0/mode_i
set_max_delay 8 -from [get_pins {u_src1/Q}] -to [get_pins {u_h0/u_mode_reg/D}]

# MERGED top=CMD000002.001 harden=CMD000006.001 boundary=u_h0/cfg_i
set_min_delay 1 -through [get_pins {u_h0/cfg_i}] -to [get_pins {u_h0/u_hold_reg/D}]

# MERGED top=CMD000002.002 harden=CMD000006.002 boundary=u_h0/mode_i
set_min_delay 1 -through [get_pins {u_h0/mode_i}] -to [get_pins {u_h0/u_hold_reg/D}]


################################################################################
# HARDEN_REMAINING_SDC inst=u_h0
# Source: /Users/howard/Documents/33_vcspyglass sdc处理/soc_sdc_work/STA Flatten 2 Set Delay Merge PrimeTime脚本/demo_case/deep_multi_mapping/harden0_clean.sdc
################################################################################
# Deep demo Stage-1-cleaned harden delay segments for u_h0.

# Case A1 harden side:
# cfg_i matches a top boundary pin. no_top_i intentionally has no matching top
# segment, so only those pair leftovers should remain. cfg_i fans to two
# endpoints, so the same top boundary pair must be reused for multiple
# generated E2E constraints.
# STAGE2_REWRITTEN CMD000004: original multi-object delay kept only for unmerged pairs
# STAGE2_ORIGINAL: set_max_delay 5.0 -from [list [get_pins u_h0/cfg_i] [get_pins u_h0/no_top_i]] -to [list [get_pins u_h0/u_cfg_reg/D] [get_pins u_h0/u_cfg_shadow_reg/D]]
set_max_delay 5 -from [get_pins {u_h0/no_top_i}] -to [get_pins {u_h0/u_cfg_reg/D}]
set_max_delay 5 -from [get_pins {u_h0/no_top_i}] -to [get_pins {u_h0/u_cfg_shadow_reg/D}]

# Case A2 harden side:
# mode_i has a different delay and a different endpoint, so generated E2E
# commands stay visually distinct from cfg_i.
# STAGE2_CONSUMED CMD000005: original delay moved to merged_delay_removed.sdc

# Case B harden side:
# Matches top open_from min delay on both cfg_i and mode_i.
# STAGE2_CONSUMED CMD000006: original delay moved to merged_delay_removed.sdc

# Case C harden side:
# Boundary input to boundary output is an output-direction / pass-through path.
# Current Stage 2 rules require review instead of automatic E2E merge.
set_max_delay 4.0 \
    -from [get_pins u_h0/pass_i] \
    -to [get_pins u_h0/pass_o]

################################################################################
# STAGE2_REVIEW_REQUIRED
# Source: /Users/howard/Documents/33_vcspyglass sdc处理/soc_sdc_work/STA Flatten 2 Set Delay Merge PrimeTime脚本/demo_case/deep_multi_mapping/unmerged_delay_review.rpt
################################################################################
# Review report: /Users/howard/Documents/33_vcspyglass sdc处理/soc_sdc_work/STA Flatten 2 Set Delay Merge PrimeTime脚本/demo_case/deep_multi_mapping/unmerged_delay_review.rpt
# The following constraints were not automatically merged:
# reason=OUTPUT_DIRECTION_NOT_SUPPORTED required_action=harden segment not mergeable harden_id=CMD000007 harden_file=/Users/howard/Documents/33_vcspyglass sdc处理/soc_sdc_work/STA Flatten 2 Set Delay Merge PrimeTime脚本/demo_case/deep_multi_mapping/harden0_clean.sdc harden_line=28
# reason=NO_TOP_SEGMENT_MATCHED required_action=no top delay segment matched harden boundary harden_id=CMD000004.003 harden_file=/Users/howard/Documents/33_vcspyglass sdc处理/soc_sdc_work/STA Flatten 2 Set Delay Merge PrimeTime脚本/demo_case/deep_multi_mapping/harden0_clean.sdc harden_line=8
# reason=NO_TOP_SEGMENT_MATCHED required_action=no top delay segment matched harden boundary harden_id=CMD000004.004 harden_file=/Users/howard/Documents/33_vcspyglass sdc处理/soc_sdc_work/STA Flatten 2 Set Delay Merge PrimeTime脚本/demo_case/deep_multi_mapping/harden0_clean.sdc harden_line=8
# reason=NO_HARDEN_SEGMENT_MATCHED required_action=top delay segment did not match any harden segment top_id=CMD000001.003 top_file=/Users/howard/Documents/33_vcspyglass sdc处理/soc_sdc_work/STA Flatten 2 Set Delay Merge PrimeTime脚本/demo_case/deep_multi_mapping/top_dc.sdc top_line=10
# reason=NO_HARDEN_SEGMENT_MATCHED required_action=top delay segment did not match any harden segment top_id=CMD000001.006 top_file=/Users/howard/Documents/33_vcspyglass sdc处理/soc_sdc_work/STA Flatten 2 Set Delay Merge PrimeTime脚本/demo_case/deep_multi_mapping/top_dc.sdc top_line=10
# reason=NO_HARDEN_SEGMENT_MATCHED required_action=top delay segment did not match any harden segment top_id=CMD000003 top_file=/Users/howard/Documents/33_vcspyglass sdc处理/soc_sdc_work/STA Flatten 2 Set Delay Merge PrimeTime脚本/demo_case/deep_multi_mapping/top_dc.sdc top_line=23
