################################################################################
# Auto-generated integration E2E delay SDC
#
# ============================================================
#   Script  : run_stage2_merge_delay.tcl
#   Stage   : STA Flatten 2 Set Delay Merge PrimeTime
#   Author  : Howard
#   Version : v0.4
# ============================================================
#
# Generated by             : run_stage2_merge_delay.tcl
# E2E_DELAY_MERGE_VERSION  : v0.4
# Scope                    : <current_integration_top>
#
# This file is generated for the current integration top scope.
# If this integration top is later consumed as a harden by an upper-level SoC,
# this file shall be reprocessed by Stage 1 hierarchy mapper.
################################################################################

# MERGED top=CMD000001.001 harden=CMD000004.001 boundary=u_h0/cfg_i
set_max_delay 7 -from [get_pins {u_src0/Q}] -to [get_pins {u_h0/u_cfg_reg/D}]

# MERGED top=CMD000001.004 harden=CMD000004.001 boundary=u_h0/cfg_i
set_max_delay 7 -from [get_pins {u_src1/Q}] -to [get_pins {u_h0/u_cfg_reg/D}]

# MERGED top=CMD000001.001 harden=CMD000004.002 boundary=u_h0/cfg_i
set_max_delay 7 -from [get_pins {u_src0/Q}] -to [get_pins {u_h0/u_cfg_shadow_reg/D}]

# MERGED top=CMD000001.004 harden=CMD000004.002 boundary=u_h0/cfg_i
set_max_delay 7 -from [get_pins {u_src1/Q}] -to [get_pins {u_h0/u_cfg_shadow_reg/D}]

# MERGED top=CMD000001.002 harden=CMD000005 boundary=u_h0/mode_i
set_max_delay 8 -from [get_pins {u_src0/Q}] -to [get_pins {u_h0/u_mode_reg/D}]

# MERGED top=CMD000001.005 harden=CMD000005 boundary=u_h0/mode_i
set_max_delay 8 -from [get_pins {u_src1/Q}] -to [get_pins {u_h0/u_mode_reg/D}]

# MERGED top=CMD000002.001 harden=CMD000006.001 boundary=u_h0/cfg_i
set_min_delay 1 -through [get_pins {u_h0/cfg_i}] -to [get_pins {u_h0/u_hold_reg/D}]

# MERGED top=CMD000002.002 harden=CMD000006.002 boundary=u_h0/mode_i
set_min_delay 1 -through [get_pins {u_h0/mode_i}] -to [get_pins {u_h0/u_hold_reg/D}]

