# ============================================================
#   Script  : run_stage2_merge_delay.tcl
#   Stage   : STA Flatten 2 Set Delay Merge PrimeTime
#   Author  : Howard
#   Version : v0.4
# ============================================================
#
# merged_delay_removed.sdc generated by run_stage2_merge_delay.tcl
# CONSUMED /Users/howard/Documents/33_vcspyglass sdc处理/soc_sdc_work/STA Flatten 2 Set Delay Merge PrimeTime脚本/demo_case/deep_multi_mapping/top_dc.sdc|CMD000001.001 original_id=CMD000001 split=1/6
# ORIGINAL: set_max_delay 2.0 -from [list [get_pins u_src0/Q] [get_pins u_src1/Q]] -to [list [get_pins u_h0/cfg_i] [get_pins u_h0/mode_i] [get_pins u_h0/unused_i]]
set_max_delay 2 -from [get_pins {u_src0/Q}] -to [get_pins {u_h0/cfg_i}]

# CONSUMED /Users/howard/Documents/33_vcspyglass sdc处理/soc_sdc_work/STA Flatten 2 Set Delay Merge PrimeTime脚本/demo_case/deep_multi_mapping/harden0_clean.sdc|CMD000004.001 original_id=CMD000004 split=1/4
# ORIGINAL: set_max_delay 5.0 -from [list [get_pins u_h0/cfg_i] [get_pins u_h0/no_top_i]] -to [list [get_pins u_h0/u_cfg_reg/D] [get_pins u_h0/u_cfg_shadow_reg/D]]
set_max_delay 5 -from [get_pins {u_h0/cfg_i}] -to [get_pins {u_h0/u_cfg_reg/D}]

# CONSUMED /Users/howard/Documents/33_vcspyglass sdc处理/soc_sdc_work/STA Flatten 2 Set Delay Merge PrimeTime脚本/demo_case/deep_multi_mapping/top_dc.sdc|CMD000001.004 original_id=CMD000001 split=4/6
# ORIGINAL: set_max_delay 2.0 -from [list [get_pins u_src0/Q] [get_pins u_src1/Q]] -to [list [get_pins u_h0/cfg_i] [get_pins u_h0/mode_i] [get_pins u_h0/unused_i]]
set_max_delay 2 -from [get_pins {u_src1/Q}] -to [get_pins {u_h0/cfg_i}]

# CONSUMED /Users/howard/Documents/33_vcspyglass sdc处理/soc_sdc_work/STA Flatten 2 Set Delay Merge PrimeTime脚本/demo_case/deep_multi_mapping/harden0_clean.sdc|CMD000004.002 original_id=CMD000004 split=2/4
# ORIGINAL: set_max_delay 5.0 -from [list [get_pins u_h0/cfg_i] [get_pins u_h0/no_top_i]] -to [list [get_pins u_h0/u_cfg_reg/D] [get_pins u_h0/u_cfg_shadow_reg/D]]
set_max_delay 5 -from [get_pins {u_h0/cfg_i}] -to [get_pins {u_h0/u_cfg_shadow_reg/D}]

# CONSUMED /Users/howard/Documents/33_vcspyglass sdc处理/soc_sdc_work/STA Flatten 2 Set Delay Merge PrimeTime脚本/demo_case/deep_multi_mapping/top_dc.sdc|CMD000001.002 original_id=CMD000001 split=2/6
# ORIGINAL: set_max_delay 2.0 -from [list [get_pins u_src0/Q] [get_pins u_src1/Q]] -to [list [get_pins u_h0/cfg_i] [get_pins u_h0/mode_i] [get_pins u_h0/unused_i]]
set_max_delay 2 -from [get_pins {u_src0/Q}] -to [get_pins {u_h0/mode_i}]

# CONSUMED /Users/howard/Documents/33_vcspyglass sdc处理/soc_sdc_work/STA Flatten 2 Set Delay Merge PrimeTime脚本/demo_case/deep_multi_mapping/harden0_clean.sdc|CMD000005 original_id=CMD000005 split=1/1
set_max_delay 6.0      -from [get_pins u_h0/mode_i]      -to [get_pins u_h0/u_mode_reg/D]

# CONSUMED /Users/howard/Documents/33_vcspyglass sdc处理/soc_sdc_work/STA Flatten 2 Set Delay Merge PrimeTime脚本/demo_case/deep_multi_mapping/top_dc.sdc|CMD000001.005 original_id=CMD000001 split=5/6
# ORIGINAL: set_max_delay 2.0 -from [list [get_pins u_src0/Q] [get_pins u_src1/Q]] -to [list [get_pins u_h0/cfg_i] [get_pins u_h0/mode_i] [get_pins u_h0/unused_i]]
set_max_delay 2 -from [get_pins {u_src1/Q}] -to [get_pins {u_h0/mode_i}]

# CONSUMED /Users/howard/Documents/33_vcspyglass sdc处理/soc_sdc_work/STA Flatten 2 Set Delay Merge PrimeTime脚本/demo_case/deep_multi_mapping/top_dc.sdc|CMD000002.001 original_id=CMD000002 split=1/2
# ORIGINAL: set_min_delay 0.3 -to [list [get_pins u_h0/cfg_i] [get_pins u_h0/mode_i]]
set_min_delay 0.3 -to [get_pins {u_h0/cfg_i}]

# CONSUMED /Users/howard/Documents/33_vcspyglass sdc处理/soc_sdc_work/STA Flatten 2 Set Delay Merge PrimeTime脚本/demo_case/deep_multi_mapping/harden0_clean.sdc|CMD000006.001 original_id=CMD000006 split=1/2
# ORIGINAL: set_min_delay 0.7 -from [list [get_pins u_h0/cfg_i] [get_pins u_h0/mode_i]] -to [get_pins u_h0/u_hold_reg/D]
set_min_delay 0.7 -from [get_pins {u_h0/cfg_i}] -to [get_pins {u_h0/u_hold_reg/D}]

# CONSUMED /Users/howard/Documents/33_vcspyglass sdc处理/soc_sdc_work/STA Flatten 2 Set Delay Merge PrimeTime脚本/demo_case/deep_multi_mapping/top_dc.sdc|CMD000002.002 original_id=CMD000002 split=2/2
# ORIGINAL: set_min_delay 0.3 -to [list [get_pins u_h0/cfg_i] [get_pins u_h0/mode_i]]
set_min_delay 0.3 -to [get_pins {u_h0/mode_i}]

# CONSUMED /Users/howard/Documents/33_vcspyglass sdc处理/soc_sdc_work/STA Flatten 2 Set Delay Merge PrimeTime脚本/demo_case/deep_multi_mapping/harden0_clean.sdc|CMD000006.002 original_id=CMD000006 split=2/2
# ORIGINAL: set_min_delay 0.7 -from [list [get_pins u_h0/cfg_i] [get_pins u_h0/mode_i]] -to [get_pins u_h0/u_hold_reg/D]
set_min_delay 0.7 -from [get_pins {u_h0/mode_i}] -to [get_pins {u_h0/u_hold_reg/D}]

